import type { ColorTheme, ThemeColors, ColorThemeInfo } from '../types';

// Helper function to create theme colors with common defaults
const createThemeColors = (
    light: Partial<ThemeColors> & Pick<ThemeColors, 'primary' | 'accent' | 'background' | 'text'>,
    dark: Partial<ThemeColors> & Pick<ThemeColors, 'primary' | 'accent' | 'background' | 'text'>
): { light: ThemeColors; dark: ThemeColors } => {
    const lightDefaults: ThemeColors = {
        surface: '#FFFFFF',
        card: '#FFFFFF',
        textSecondary: '#666666',
        textMuted: '#999999',
        primaryLight: light.primary + '80', // Add transparency as fallback
        primaryDark: light.primary,
        accentLight: light.accent + '80',
        border: '#E0E0E0',
        divider: '#F0F0F0',
        overlay: 'rgba(0, 0, 0, 0.5)',
        success: '#4CAF50',
        warning: '#FF9800',
        error: '#FF5722',
        info: '#2196F3',
        buttonBackground: light.primary,
        buttonText: '#FFFFFF',
        switchTrack: '#CCCCCC',
        switchThumb: '#FFFFFF',
        questionCardBackground: '#FFFFFF',
        questionCardBorder: '#F0F0F0',
        questionIdBackground: '#F0F0F0',
        headerBackground: light.primary,
        headerText: '#FFFFFF',
        modalBackground: '#FFFFFF',
        modalOverlay: 'rgba(0, 0, 0, 0.5)',
        vibrant1: light.accent,
        vibrant2: light.primary,
        vibrant3: light.primary,
        gradient1: light.primary,
        gradient2: light.accent,
        ...light,
    };

    const darkDefaults: ThemeColors = {
        surface: '#1E1E1E',
        card: '#2D2D2D',
        textSecondary: '#CCCCCC',
        textMuted: '#999999',
        primaryLight: dark.primary + '80',
        primaryDark: dark.primary,
        accentLight: dark.accent + '80',
        border: '#404040',
        divider: '#333333',
        overlay: 'rgba(0, 0, 0, 0.7)',
        success: '#66BB6A',
        warning: '#FFA726',
        error: '#EF5350',
        info: '#42A5F5',
        buttonBackground: dark.primary,
        buttonText: '#FFFFFF',
        switchTrack: '#666666',
        switchThumb: '#FFFFFF',
        questionCardBackground: '#2D2D2D',
        questionCardBorder: '#404040',
        questionIdBackground: '#404040',
        headerBackground: '#1E1E1E',
        headerText: '#FFFFFF',
        modalBackground: '#2D2D2D',
        modalOverlay: 'rgba(0, 0, 0, 0.8)',
        vibrant1: dark.accent,
        vibrant2: dark.primary,
        vibrant3: dark.primary,
        gradient1: dark.primary,
        gradient2: dark.accent,
        ...dark,
    };

    return { light: lightDefaults, dark: darkDefaults };
};

// Color theme configurations
export const colorThemes: Record<ColorTheme, { light: ThemeColors; dark: ThemeColors }> = {
    classic: createThemeColors(
        {
            background: '#F5F5F5',
            text: '#333333',
            primary: '#3F51B5',
            accent: '#FF4081',
            primaryLight: '#7986CB',
            primaryDark: '#303F9F',
            accentLight: '#FF79B0',
            vibrant1: '#E91E63',
            vibrant2: '#9C27B0',
            vibrant3: '#3F51B5',
        },
        {
            background: '#121212',
            text: '#FFFFFF',
            primary: '#5C6BC0',
            accent: '#FF4081',
            primaryLight: '#8E99F3',
            primaryDark: '#3F4BA0',
            accentLight: '#FF79B0',
            vibrant1: '#F06292',
            vibrant2: '#BA68C8',
            vibrant3: '#7986CB',
        }
    ),

    ocean: createThemeColors(
        {
            background: '#F0F8FF',
            text: '#1A365D',
            primary: '#0080FF',
            accent: '#00D4AA',
            textSecondary: '#2D3748',
            textMuted: '#718096',
            primaryLight: '#42A5F5',
            primaryDark: '#0056B3',
            accentLight: '#4FD1C7',
            border: '#E2E8F0',
            divider: '#EDF2F7',
            overlay: 'rgba(26, 54, 93, 0.5)',
            success: '#48BB78',
            warning: '#ED8936',
            error: '#F56565',
            info: '#4299E1',
            switchTrack: '#CBD5E0',
            questionIdBackground: '#EBF8FF',
            modalOverlay: 'rgba(26, 54, 93, 0.5)',
            vibrant1: '#00D4AA',
            vibrant2: '#0080FF',
            vibrant3: '#38B2AC',
        },
        {
            background: '#0F1419',
            text: '#F7FAFC',
            primary: '#42A5F5',
            accent: '#4FD1C7',
            surface: '#1A202C',
            card: '#2D3748',
            textSecondary: '#E2E8F0',
            textMuted: '#A0AEC0',
            primaryLight: '#64B5F6',
            primaryDark: '#1E88E5',
            accentLight: '#81E6D9',
            border: '#4A5568',
            divider: '#2D3748',
            overlay: 'rgba(15, 20, 25, 0.8)',
            success: '#68D391',
            warning: '#F6AD55',
            error: '#FC8181',
            info: '#63B3ED',
            switchTrack: '#4A5568',
            questionIdBackground: '#1A365D',
            headerBackground: '#1A202C',
            headerText: '#F7FAFC',
            modalOverlay: 'rgba(15, 20, 25, 0.9)',
            vibrant1: '#4FD1C7',
            vibrant2: '#42A5F5',
            vibrant3: '#68D391',
        }
    ),

    sunset: createThemeColors(
        {
            background: '#FFF8F0',
            text: '#7C2D12',
            primary: '#FF6B35',
            accent: '#FFD60A',
            textSecondary: '#9A3412',
            textMuted: '#A16207',
            primaryLight: '#FF8A65',
            primaryDark: '#E64A19',
            accentLight: '#FFF176',
            border: '#FED7AA',
            divider: '#FEF3C7',
            overlay: 'rgba(124, 45, 18, 0.5)',
            success: '#65A30D',
            warning: '#F59E0B',
            error: '#DC2626',
            info: '#3B82F6',
            switchTrack: '#FED7AA',
            questionIdBackground: '#FEF3C7',
            modalOverlay: 'rgba(124, 45, 18, 0.5)',
            vibrant1: '#FFD60A',
            vibrant2: '#FF6B35',
            vibrant3: '#F97316',
        },
        {
            background: '#1C0F0A',
            text: '#FFF8F0',
            primary: '#FF8A65',
            accent: '#FFF176',
            surface: '#2D1B14',
            card: '#44281D',
            textSecondary: '#FED7AA',
            textMuted: '#D97706',
            primaryLight: '#FFAB91',
            primaryDark: '#FF5722',
            accentLight: '#FFF59D',
            border: '#78350F',
            divider: '#44281D',
            overlay: 'rgba(28, 15, 10, 0.8)',
            success: '#84CC16',
            warning: '#FBBF24',
            error: '#EF4444',
            info: '#60A5FA',
            switchTrack: '#78350F',
            questionIdBackground: '#2D1B14',
            headerBackground: '#2D1B14',
            headerText: '#FFF8F0',
            modalOverlay: 'rgba(28, 15, 10, 0.9)',
            vibrant1: '#FFF176',
            vibrant2: '#FF8A65',
            vibrant3: '#FBBF24',
        }
    ),

    forest: createThemeColors(
        {
            background: '#F0FDF4',
            text: '#14532D',
            primary: '#16A34A',
            accent: '#84CC16',
            textSecondary: '#166534',
            textMuted: '#15803D',
            primaryLight: '#4ADE80',
            primaryDark: '#15803D',
            accentLight: '#A3E635',
            border: '#BBF7D0',
            divider: '#DCFCE7',
            overlay: 'rgba(20, 83, 45, 0.5)',
            success: '#22C55E',
            warning: '#F59E0B',
            error: '#EF4444',
            info: '#3B82F6',
            switchTrack: '#BBF7D0',
            questionIdBackground: '#DCFCE7',
            modalOverlay: 'rgba(20, 83, 45, 0.5)',
            vibrant1: '#84CC16',
            vibrant2: '#16A34A',
            vibrant3: '#22C55E',
        },
        {
            background: '#0C1C0E',
            text: '#F0FDF4',
            primary: '#4ADE80',
            accent: '#A3E635',
            surface: '#14532D',
            card: '#166534',
            textSecondary: '#BBF7D0',
            textMuted: '#86EFAC',
            primaryLight: '#6EE7B7',
            primaryDark: '#22C55E',
            accentLight: '#BEF264',
            border: '#15803D',
            divider: '#14532D',
            overlay: 'rgba(12, 28, 14, 0.8)',
            success: '#22D3EE',
            warning: '#FBBF24',
            error: '#F87171',
            info: '#60A5FA',
            buttonText: '#14532D',
            switchTrack: '#15803D',
            questionIdBackground: '#14532D',
            headerBackground: '#14532D',
            headerText: '#F0FDF4',
            modalOverlay: 'rgba(12, 28, 14, 0.9)',
            vibrant1: '#A3E635',
            vibrant2: '#4ADE80',
            vibrant3: '#22D3EE',
        }
    ),

    lavender: createThemeColors(
        {
            background: '#FAF5FF',
            text: '#581C87',
            primary: '#A855F7',
            accent: '#EC4899',
            textSecondary: '#7C3AED',
            textMuted: '#A855F7',
            primaryLight: '#C084FC',
            primaryDark: '#9333EA',
            accentLight: '#F472B6',
            border: '#E9D5FF',
            divider: '#F3E8FF',
            overlay: 'rgba(88, 28, 135, 0.5)',
            success: '#10B981',
            warning: '#F59E0B',
            error: '#EF4444',
            info: '#3B82F6',
            switchTrack: '#E9D5FF',
            questionIdBackground: '#F3E8FF',
            modalOverlay: 'rgba(88, 28, 135, 0.5)',
            vibrant1: '#EC4899',
            vibrant2: '#A855F7',
            vibrant3: '#8B5CF6',
        },
        {
            background: '#1E0A2E',
            text: '#FAF5FF',
            primary: '#C084FC',
            accent: '#F472B6',
            surface: '#2E1065',
            card: '#3730A3',
            textSecondary: '#E9D5FF',
            textMuted: '#C4B5FD',
            primaryLight: '#DDD6FE',
            primaryDark: '#A855F7',
            accentLight: '#F9A8D4',
            border: '#6D28D9',
            divider: '#3730A3',
            overlay: 'rgba(30, 10, 46, 0.8)',
            success: '#34D399',
            warning: '#FBBF24',
            error: '#F87171',
            info: '#60A5FA',
            buttonText: '#1E0A2E',
            switchTrack: '#6D28D9',
            questionIdBackground: '#2E1065',
            headerBackground: '#2E1065',
            headerText: '#FAF5FF',
            modalOverlay: 'rgba(30, 10, 46, 0.9)',
            vibrant1: '#F472B6',
            vibrant2: '#C084FC',
            vibrant3: '#8B5CF6',
        }
    ),

    coral: createThemeColors(
        {
            background: '#FEF7ED',
            text: '#9A3412',
            primary: '#FF6B6B',
            accent: '#4ECDC4',
            textSecondary: '#C2410C',
            textMuted: '#F97316',
            primaryLight: '#FF8E8E',
            primaryDark: '#E55353',
            accentLight: '#81E6D9',
            border: '#FED7AA',
            divider: '#FEF3C7',
            overlay: 'rgba(154, 52, 18, 0.5)',
            success: '#06D6A0',
            warning: '#FFD93D',
            error: '#EF476F',
            info: '#118AB2',
            switchTrack: '#FED7AA',
            questionIdBackground: '#FEF3C7',
            modalOverlay: 'rgba(154, 52, 18, 0.5)',
            vibrant1: '#4ECDC4',
            vibrant2: '#FF6B6B',
            vibrant3: '#FFD93D',
        },
        {
            background: '#2C1810',
            text: '#FEF7ED',
            primary: '#FF8E8E',
            accent: '#81E6D9',
            surface: '#3D2817',
            card: '#4A2C17',
            textSecondary: '#FED7AA',
            textMuted: '#FDBA74',
            primaryLight: '#FFA8A8',
            primaryDark: '#FF6B6B',
            accentLight: '#B2F5EA',
            border: '#78350F',
            divider: '#4A2C17',
            overlay: 'rgba(44, 24, 16, 0.8)',
            success: '#34D399',
            warning: '#FBBF24',
            error: '#F87171',
            info: '#60A5FA',
            buttonText: '#2C1810',
            switchTrack: '#78350F',
            questionIdBackground: '#3D2817',
            headerBackground: '#3D2817',
            headerText: '#FEF7ED',
            modalOverlay: 'rgba(44, 24, 16, 0.9)',
            vibrant1: '#81E6D9',
            vibrant2: '#FF8E8E',
            vibrant3: '#FBBF24',
        }
    ),

    midnight: createThemeColors(
        {
            background: '#F8FAFC',
            text: '#1E293B',
            primary: '#6366F1',
            accent: '#EC4899',
            textSecondary: '#334155',
            textMuted: '#64748B',
            primaryLight: '#818CF8',
            primaryDark: '#4F46E5',
            accentLight: '#F472B6',
            border: '#E2E8F0',
            divider: '#F1F5F9',
            overlay: 'rgba(30, 41, 59, 0.5)',
            success: '#10B981',
            warning: '#F59E0B',
            error: '#EF4444',
            info: '#06B6D4',
            switchTrack: '#CBD5E0',
            questionIdBackground: '#F1F5F9',
            modalOverlay: 'rgba(30, 41, 59, 0.5)',
            vibrant1: '#EC4899',
            vibrant2: '#6366F1',
            vibrant3: '#06B6D4',
        },
        {
            background: '#0F0F23',
            text: '#F8FAFC',
            primary: '#818CF8',
            accent: '#F472B6',
            surface: '#1E1E3F',
            card: '#2A2A54',
            textSecondary: '#CBD5E0',
            textMuted: '#94A3B8',
            primaryLight: '#A5B4FC',
            primaryDark: '#6366F1',
            accentLight: '#F9A8D4',
            border: '#3C3C69',
            divider: '#2A2A54',
            overlay: 'rgba(15, 15, 35, 0.8)',
            success: '#34D399',
            warning: '#FBBF24',
            error: '#F87171',
            info: '#22D3EE',
            buttonText: '#0F0F23',
            switchTrack: '#3C3C69',
            questionIdBackground: '#1E1E3F',
            headerBackground: '#1E1E3F',
            headerText: '#F8FAFC',
            modalOverlay: 'rgba(15, 15, 35, 0.9)',
            vibrant1: '#F472B6',
            vibrant2: '#818CF8',
            vibrant3: '#22D3EE',
        }
    ),

    neon: createThemeColors(
        {
            background: '#FAFAFA',
            text: '#0A0A0A',
            primary: '#00FF88',
            accent: '#FF0080',
            textSecondary: '#333333',
            textMuted: '#666666',
            primaryLight: '#66FFA8',
            primaryDark: '#00CC6A',
            accentLight: '#FF66B0',
            border: '#E0E0E0',
            divider: '#F0F0F0',
            overlay: 'rgba(10, 10, 10, 0.5)',
            success: '#00FF88',
            warning: '#FFFF00',
            error: '#FF0040',
            info: '#00BFFF',
            buttonText: '#0A0A0A',
            switchTrack: '#E0E0E0',
            questionIdBackground: '#F0F0F0',
            headerText: '#0A0A0A',
            modalOverlay: 'rgba(10, 10, 10, 0.5)',
            vibrant1: '#FF0080',
            vibrant2: '#00FF88',
            vibrant3: '#00BFFF',
        },
        {
            background: '#0A0A0A',
            text: '#FFFFFF',
            primary: '#00FF88',
            accent: '#FF0080',
            surface: '#1A1A1A',
            card: '#2A2A2A',
            textSecondary: '#CCCCCC',
            textMuted: '#999999',
            primaryLight: '#66FFA8',
            primaryDark: '#00CC6A',
            accentLight: '#FF66B0',
            border: '#333333',
            divider: '#2A2A2A',
            overlay: 'rgba(10, 10, 10, 0.8)',
            success: '#00FF88',
            warning: '#FFFF00',
            error: '#FF0040',
            info: '#00BFFF',
            buttonText: '#0A0A0A',
            switchTrack: '#333333',
            questionIdBackground: '#1A1A1A',
            headerBackground: '#1A1A1A',
            headerText: '#FFFFFF',
            modalOverlay: 'rgba(10, 10, 10, 0.9)',
            vibrant1: '#FF0080',
            vibrant2: '#00FF88',
            vibrant3: '#00BFFF',
        }
    ),
};

// Color theme information for UI display
export const colorThemeInfo: Record<ColorTheme, ColorThemeInfo> = {
    classic: {
        id: 'classic',
        name: 'Classic Blue',
        description: 'Traditional and professional',
        primaryColor: '#3F51B5',
        accentColor: '#FF4081',
    },
    ocean: {
        id: 'ocean',
        name: 'Ocean Breeze',
        description: 'Calm and refreshing',
        primaryColor: '#0080FF',
        accentColor: '#00D4AA',
        isGradient: true,
    },
    sunset: {
        id: 'sunset',
        name: 'Sunset Glow',
        description: 'Warm and energetic',
        primaryColor: '#FF6B35',
        accentColor: '#FFD60A',
        isGradient: true,
    },
    forest: {
        id: 'forest',
        name: 'Forest Fresh',
        description: 'Natural and peaceful',
        primaryColor: '#16A34A',
        accentColor: '#84CC16',
    },
    lavender: {
        id: 'lavender',
        name: 'Lavender Dream',
        description: 'Elegant and dreamy',
        primaryColor: '#A855F7',
        accentColor: '#EC4899',
        isGradient: true,
    },
    coral: {
        id: 'coral',
        name: 'Coral Reef',
        description: 'Vibrant and playful',
        primaryColor: '#FF6B6B',
        accentColor: '#4ECDC4',
        isGradient: true,
    },
    midnight: {
        id: 'midnight',
        name: 'Midnight Sky',
        description: 'Mysterious and modern',
        primaryColor: '#6366F1',
        accentColor: '#EC4899',
        isGradient: true,
    },
    neon: {
        id: 'neon',
        name: 'Neon Lights',
        description: 'Bold and futuristic',
        primaryColor: '#00FF88',
        accentColor: '#FF0080',
        isGradient: true,
    },
};