import type { IconMapping, JsonIconMapping, JsonIconColorMapping, Icon3DVariant } from '../types';

// Base icon names mapped to Ionicons
const baseIcons = {
    home: 'home',
    search: 'search',
    settings: 'settings',
    categories: 'grid',
    chevronDown: 'chevron-down',
    chevronUp: 'chevron-up',
    chevronForward: 'chevron-forward',
    chevronBack: 'chevron-back',
    close: 'close',
    textFormat: 'text',
    share: 'share-social',
    star: 'star',
    info: 'information-circle',
    refresh: 'refresh',
    sun: 'sunny',
    moon: 'moon',
    palette: 'color-palette',
    image: 'image',
    expand: 'expand',
    collapse: 'contract',
    analytics: 'analytics',
    helpCircle: 'help-circle',
    time: 'time',
    checkmark: 'checkmark',
    checkmarkCircle: 'checkmark-circle',
    play: 'play',
    trophy: 'trophy',
    eye: 'eye',
    bulb: 'bulb',
    alertCircle: 'alert-circle',
    trendingUp: 'trending-up',
    shuffle: 'shuffle',
    bug: 'bug',
    grid: 'grid',
    flash: 'flash',
    people: 'people',
    chatbox: 'chatbox',
    arrowBack: 'arrow-back',
} as const;

export const iconSets: IconMapping = baseIcons;

// Category icons for JSON data files
export const jsonIconSets: JsonIconMapping = {
    map: 'map',
    person: 'person',
    book: 'book',
    business: 'business',
    star: 'star',
    flag: 'flag',
    shield: 'shield',
    people: 'people',
    cash: 'cash',
    library: 'library',
    brush: 'brush',
    football: 'football',
    calendar: 'calendar',
    default: 'help-circle',
};

// Color mapping for JSON category icons
export const jsonIconColors: JsonIconColorMapping = {
    map: '#00B4D8',
    person: '#9D4EDD',
    book: '#F77F00',
    business: '#06D6A0',
    star: '#FFD60A',
    flag: '#EF476F',
    shield: '#118AB2',
    people: '#F72585',
    cash: '#43AA8B',
    library: '#7209B7',
    brush: '#FF006E',
    football: '#FB5607',
    calendar: '#8338EC',
    default: '#6C757D',
};

// 3D variant assignments for UI icons
export const iconVariantMap: Record<keyof IconMapping, Icon3DVariant> = {
    home: 'gradient',
    search: 'glass',
    settings: 'elevated',
    categories: 'elevated',
    chevronDown: 'default',
    chevronUp: 'default',
    chevronForward: 'default',
    chevronBack: 'default',
    close: 'glass',
    textFormat: 'glass',
    share: 'elevated',
    star: 'neon',
    info: 'glass',
    refresh: 'glass',
    sun: 'neon',
    moon: 'neon',
    palette: 'gradient',
    image: 'glass',
    expand: 'default',
    collapse: 'default',
    analytics: 'gradient',
    helpCircle: 'glass',
    time: 'glass',
    checkmark: 'elevated',
    checkmarkCircle: 'elevated',
    play: 'gradient',
    trophy: 'neon',
    eye: 'glass',
    bulb: 'neon',
    alertCircle: 'elevated',
    trendingUp: 'gradient',
    shuffle: 'glass',
    bug: 'glass',
    grid: 'elevated',
    flash: 'neon',
    people: 'elevated',
    chatbox: 'glass',
    arrowBack: 'default',
};

// 3D variant assignments for JSON category icons
export const jsonIconVariantMap: Record<keyof JsonIconMapping, Icon3DVariant> = {
    map: 'elevated',
    person: 'elevated',
    book: 'elevated',
    business: 'elevated',
    star: 'elevated',
    flag: 'elevated',
    shield: 'elevated',
    people: 'elevated',
    cash: 'elevated',
    library: 'elevated',
    brush: 'elevated',
    football: 'elevated',
    calendar: 'elevated',
    default: 'glass',
};